// Pregenerate ElevenLabs TTS once for every Japanese string that drill
// surfaces speak. Outputs:
//   - public/tts/<sha1(voice:model:text)>.mp3   (content-addressed, cacheable)
//   - src/lib/tts-manifest.ts                   (text → filename map, shipped to the browser)
//
// Re-runs are cheap: anything already on disk is skipped. Deleting a file
// forces a regenerate. Changing DEFAULT_VOICE or DEFAULT_MODEL changes every
// hash and triggers a full regen (as it should — a new voice is new audio).
//
// Run: npm run tts:generate

import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";

import { DEFAULT_VOICE, DEFAULT_MODEL, VOICE_SETTINGS } from "../src/lib/tts-config";
import { vocab } from "../src/data/vocab";
import { kanji } from "../src/data/kanji";
import { grammar } from "../src/data/grammar";
import { hiragana, katakana } from "../src/data/kana";

// Load .env.local so the API key is available when running the script.
// Next.js loads this at runtime; the script runs standalone so we load it
// manually. Falls through silently if the file is missing.
async function loadEnvLocal() {
  try {
    const txt = await fs.readFile(path.resolve(process.cwd(), ".env.local"), "utf8");
    for (const line of txt.split(/\r?\n/)) {
      const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
      if (!m) continue;
      const [, k, v] = m;
      if (!process.env[k]) process.env[k] = v.trim();
    }
  } catch {
    // No .env.local — hope env is set another way.
  }
}

const OUT_DIR = path.resolve(process.cwd(), "public/tts");
const MANIFEST_PATH = path.resolve(process.cwd(), "src/lib/tts-manifest.ts");

function hashKey(text: string) {
  return crypto
    .createHash("sha1")
    .update(`${DEFAULT_VOICE}:${DEFAULT_MODEL}:${text}`)
    .digest("hex")
    .slice(0, 16);
}

// Collect the exhaustive set of strings the app can ever ask to speak.
// Mirrors the logic in each page so filenames line up.
function collectStrings(): string[] {
  const set = new Set<string>();

  for (const v of vocab) set.add(v.word);

  for (const k of kanji) {
    // kanji/page.tsx: `card.examples[0]?.word ?? card.kanji`
    const phrase = k.examples[0]?.word ?? k.kanji;
    set.add(phrase);
  }

  for (const lesson of grammar) {
    for (const ex of lesson.examples) set.add(ex.jp);
  }

  for (const p of hiragana) set.add(p.kana);
  for (const p of katakana) set.add(p.kana);

  return [...set].filter(Boolean);
}

async function fetchMp3(text: string, apiKey: string): Promise<Buffer> {
  const url = `https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(
    DEFAULT_VOICE,
  )}/stream?optimize_streaming_latency=3`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "xi-api-key": apiKey,
      "Content-Type": "application/json",
      Accept: "audio/mpeg",
    },
    body: JSON.stringify({
      text,
      model_id: DEFAULT_MODEL,
      voice_settings: VOICE_SETTINGS,
    }),
  });
  if (!res.ok) {
    const err = await res.text().catch(() => "");
    throw new Error(`ElevenLabs ${res.status}: ${err.slice(0, 300)}`);
  }
  return Buffer.from(await res.arrayBuffer());
}

async function writeManifest(entries: Array<[string, string]>) {
  // Sort by text so the manifest diffs are stable when content is added.
  entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const header = [
    "// AUTO-GENERATED by scripts/generate-tts.ts — do not edit by hand.",
    "// Maps a Japanese phrase to the pregenerated MP3 filename in /public/tts/.",
    "// Regenerate: npm run tts:generate",
    "",
    "export const ttsManifest: Record<string, string> = {",
  ].join("\n");
  const body = entries
    .map(([text, hash]) => `  ${JSON.stringify(text)}: ${JSON.stringify(hash)},`)
    .join("\n");
  const footer = "};\n";
  await fs.writeFile(MANIFEST_PATH, `${header}\n${body}\n${footer}`, "utf8");
}

async function main() {
  await loadEnvLocal();
  const rawKey = process.env.ELEVENLABS_API_KEY;
  if (!rawKey) {
    console.error("ELEVENLABS_API_KEY is not set (looked in env and .env.local).");
    process.exit(1);
  }
  const apiKey: string = rawKey;

  await fs.mkdir(OUT_DIR, { recursive: true });

  const strings = collectStrings();
  console.log(`[tts] ${strings.length} unique phrases to check.`);

  const manifestEntries: Array<[string, string]> = [];
  let generated = 0;
  let skipped = 0;
  let failed = 0;

  // Modest concurrency — ElevenLabs rate-limits, and sequential-ish is kinder.
  const CONCURRENCY = 4;
  let idx = 0;
  async function worker() {
    while (true) {
      const i = idx++;
      if (i >= strings.length) return;
      const text = strings[i];
      const hash = hashKey(text);
      const file = path.join(OUT_DIR, `${hash}.mp3`);
      manifestEntries.push([text, hash]);
      try {
        await fs.access(file);
        skipped++;
        continue;
      } catch {
        // not on disk — generate
      }
      try {
        const mp3 = await fetchMp3(text, apiKey);
        await fs.writeFile(file, mp3);
        generated++;
        if (generated % 25 === 0) {
          console.log(`[tts] generated ${generated}, skipped ${skipped}...`);
        }
      } catch (err) {
        failed++;
        console.error(
          `[tts] FAIL "${text}":`,
          err instanceof Error ? err.message : String(err),
        );
      }
    }
  }

  await Promise.all(Array.from({ length: CONCURRENCY }, () => worker()));

  await writeManifest(manifestEntries);

  console.log(
    `[tts] done. generated=${generated} skipped=${skipped} failed=${failed} total=${strings.length}`,
  );
  console.log(`[tts] manifest written to ${path.relative(process.cwd(), MANIFEST_PATH)}`);
  if (failed > 0) process.exit(1);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
